### ISSUE TITLE
docker-compose documentation includes quotes for env variables

### ISSUE THREAD

**Issue by adamkf** [Chia-Network/chia-docker#116]
The docker compose section erroneously includes quotes in the "environment" section of readme.md.  This is not how docker compose is supposed to work and causes strings to be ignored and incorrectly parsed:

```
version: "3.6"
services:
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    ports:
      - 8444:8444
    environment:
      # Farmer Only    
#     - farmer="true"
      # Harvester Only
#     - harvester="true"
#     - farmer_address="192.168.0.10" 
#     - farmer_port="8447"
#     - ca="/path/in/container"
#     - keys="copy"
      # Harvester Only END
      # If you would like to add keys manually via mnemonic file
#     - keys="/path/in/container"
      # OR
      # Disable key generation on start
#     - keys=""
      - TZ=${TZ}
    volumes:
      - /path/to/plots:/plots
      - /home/user/.chia:/root/.chia
#     - /home/user/mnemonic:/path/in/container
```

should actually read as:

```
version: "3.6"
services:
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    ports:
      - 8444:8444
    environment:
      # Farmer Only    
#     - farmer=true
      # Harvester Only
#     - harvester=true
#     - farmer_address=192.168.0.10 
#     - farmer_port=8447
#     - ca=/path/in/container
#     - keys=copy
      # Harvester Only END
      # If you would like to add keys manually via mnemonic file
#     - keys=/path/in/container
      # OR
      # Disable key generation on start
#     - keys=
      - TZ=${TZ}
    volumes:
      - /path/to/plots:/plots
      - /home/user/.chia:/root/.chia
#     - /home/user/mnemonic:/path/in/container
```

Hopefully this saves someone else a bit of time.
