### ISSUE TITLE
Connect local GUI to docker?

### ISSUE THREAD

**Issue by n8henrie** [Chia-Network/chia-docker#120]
For convenience and reliability, I'm running chia through Docker on a Linux host.

Is it possible for me to run the GUI and connect to the farmer that is already running?

Would I need to do anything other than publish `55400:55400`?

It seems like most of the [remote daemon instructions](https://github.com/Chia-Network/chia-blockchain/wiki/Connecting-the-UI-to-a-remote-daemon) wouldn't apply, since it is all still running on  / accessible through localhost.

**Comment by n8henrie** [comment]
Bump

**Comment by acseven** [comment]
Editing these below in the client's (the machine where you want to open the GUI) `config.yaml` works for me (both for just accessing the remote machine and harvesting):

```
ui:
  daemon_host: {your remote chia full node IP}
  daemon_port: 55400
(...)
  farmer_peer:
    host: {your remote chia full node IP}
```

And publishing port 55440, as you've already mentioned.
