### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8555

### ISSUE THREAD

**Issue by sibitha-bijesh** [Chia-Network/chia-docker#13]
Hello ,

I got following error when I tried to connect via docker container . Attached my docker-compose file.  Can you please let me know how do I establish connection from app container .   
```
class RpcClient {
  constructor(options) {
    this.port = options.port;
    this.agent = new Agent({
      rejectUnauthorized: false,
      cert:  fs.readFileSync(path.resolve(__dirname, certPath)),
      key: fs.readFileSync(path.resolve(__dirname, keyPath)),
    });
  }

  baseUri() {
    return `https://localhost:${this.port}`;
  }

  async request(route, body) {
    const url = `${this.baseUri()}/${route}`;
    console.log(url);
    const { data } = await axios.post(url, body, {
      httpsAgent: this.agent,
    });

    return data;
  }
}

module.exports = RpcClient;
````

docker compose file 
````
version: '3.6'
services:
  chianet:
    image: ghcr.io/chia-network/chia
    restart: always
    networks: 
      - dotin
  app:
    container_name: app
    restart: always
    ports:
      - 3001:3001
    build:
      context: app
      dockerfile: Dockerfile    
    depends_on:
      - chianet
    links:
      - "chianet"   
    command: npm run start    
    networks: 
      - dotin   

volumes:
  db_data:

networks:
  default:
  ````

```
syncError: Error: connect ECONNREFUSED 127.0.0.1:8555
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 8555,
    config: {
      url: 'https://localhost:8555/get_blockchain_state',
      ```
