### ISSUE TITLE
docker harvester stops if recursive dir is empty or errors at some point.

### ISSUE THREAD

**Issue by chilio** [Chia-Network/chia-docker#187]
This is kind of a feature request, but I think it is pretty important.
When this image is run with `-e recursive_plot_scan="true" `  and container hits empty or errored target directory/mount, this harvester becomes obsolete with zero plots.
I believe the correct behavior would be to read all dirs (under the selected parent directory) and add all available/accesible plots to the chia harvester, even though some dirs might not be readable.

**Comment by Starttoaster** [comment]
For my context, is that the behavior of the Chia harvester process, or a behavior you've noticed to be specific to the harvester when ran inside a docker container?

**Comment by chilio** [comment]
I though the `-e recursive_plot_scan="true"` directive works only in docker environment, so I haven't tested this any other way.
And I can double confirm the docker harverster is started with 0 attached plots, when any of mounted subdirectories is just empty (not even an error one)

**Comment by Starttoaster** [comment]
Without more information, this Issue seems like it would belong to the chia-blockchain repository. The `recursive_plot_scan` feature is made available through code in the chia-blockchain repository and is only supported in this repository by setting it in your Chia config.yaml if you configure the environment variable.

**Comment by Starttoaster** [comment]
This isn't the behavior of the recursive plot scan feature that I'm seeing in the container either. Using this docker-compose.yml file:

```
version: "3.6"
services:
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    environment:
      plots_dir: /mnt
      keys: /key.txt
      recursive_plot_scan: "true"
    volumes:
      - /mnt:/mnt
      - /home/bb/key.txt:/key.txt
 ```

My `/mnt` directory contains several subdirectories with plots in them, and one empty subdirectory named `tempplots`. These are all mounted in the container, and on `chia farm summary` I see `Local Harvester 633 plots of size: 62.657 TiB`. 

Running `du -h /mnt` on my host, I see that the total contents come out to `63TB`, so it adds up on my end.

**Comment by Starttoaster** [comment]
Here's some output to show my directory tree:

```
bb@chia1:~$ tree /mnt
/mnt
├── final1
├── final10
│   ├── plot-k32-...plot (and more listed below this)
├── final12
├── final2
│   ├── plot-k32-...plot (and more listed below this)
├── final3
├── final4
├── final5
│   ├── lost+found
│   ├── plot-k32-...plot (and more listed below this)
├── final6
│   ├── plot-k32-...plot (and more listed below this)
├── final7
│   ├── plot-k32-...plot (and more listed below this)
├── final9
│   ├── plot-k32-...plot (and more listed below this)
└── tempplots

16 directories, 633 files
```

There are other directories that are also empty. I lost a few drives over time (we had a few heat waves in my neck of the woods that helped to fry a couple.)

**Comment by chilio** [comment]
@Starttoaster can you confirm the same if any of the directories are not readable due to for example faulty hdd?

**Comment by Starttoaster** [comment]
I can. I mentioned earlier that I've lost a few drives. I guess I never mentioned that the failed drives are still hooked up though.

Running an lsblk on my server, I see this unmounted partition. This 10TB (9.1T according to lsblk) drive used to store plots. But has since gone bad for one reason or another, I have yet to run testdisk to see if I can recover the plots off of it. 
```
sdb                         8:16   0   9.1T  0 disk
└─sdb1                      8:17   0   9.1T  0 part
```
Attempting to mount that drive returns this error:
```
bb@chia1:~$ sudo mount /dev/sdb1 /mnt/final1
mount: /mnt/final1: can't read superblock on /dev/sdb1.
```
/mnt/final1 used to be one of my plot directories but is now just an empty directory after the drive failed.

Then I start up my Chia farm with a docker-compose file looking like the following
```
version: "3.6"
services:
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    environment:
      # generic config
      TZ: "America/Vancouver"
      log_level: "INFO"
      service: "farmer"

      # plots config
      plots_dir: /mnt
      recursive_plot_scan: "true"

      # key config
      keys: "persistent"
    volumes:
      # plots
      - /mnt:/mnt
      # chia root (db, config, cache files, etc)
      - /home/bb/.chia/mainnet:/root/.chia/mainnet
      # chia keys
      - /home/bb/.chia_keys:/root/.chia_keys
```
The container starts up fine. Execing into the container I can check my farm summary to see if my harvester found its plots:
```
bb@chia1:~$ docker exec -it chia /bin/bash
root@1daf0bd5317b:/chia-blockchain# . ./activate
(venv) root@1daf0bd5317b:/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 28.000000000019
User transaction fees: 1.9e-11
Block rewards: 28.0
Last height farmed: 3376023
Local Harvester
   633 plots of size: 62.657 TiB
Plot count for all harvesters: 633
Total size of plots: 62.657 TiB
Estimated network space: 21.925 EiB
Expected time to win: 2 months and 1 week
Note: log into your key using 'chia wallet show' to see rewards for each key
```
Success :) That's the expected plot count for my farm.

In summary, I also have failed hard drives, and am using the recursive plot scanning feature, and my harvester in the container is able to resolve the plots that still exist how I'd expect it to.

Going back, I asked for more details on your particular setup, because without more information, this seems potentially like an edge case that may only happen under particular circumstances, or just specific to your farm.

Alternatively... You may also want to attempt to disconnect your failed hard drives and recycle them! :)
