### ISSUE TITLE
arm image

### ISSUE THREAD

**Issue by Tezonis** [Chia-Network/chia-docker#20]
Hi,

I would have like to test Chia on my NAS via Docker, but I get the following error message in the container log at launch:
```
standard_init_linux.go:219: exec user process caused: exec format error
```
This usually means that the image has the wrong architecture, my NAS is an ARM64 armbian.
I'm using image **ghcr.io/chia-network/chia:latest**.

I see a [Chia-Docker-Arm.yml](https://github.com/Chia-Network/chia-docker/blob/main/.github/workflows/Chia-Docker-Arm.yml), I don't know how it works, but it sounds like the image should support arm?
I could try the Raspberry Pi installation which is very close to my armbian based NAS, but I would prefer to use Docker.

**Comment by justinengland** [comment]
this docker image does not support arm atm. that arm build is for the chia gui installer.

**Comment by justinengland** [comment]
i think this is a valid feature request though. have my thumb up. ill add it to the todo list.

**Comment by Cyber1000** [comment]
# 2 Options
- disclaimer: it will work on anything which is more like a full linux-system, like a rpi (testet on rpi4 with raspbery os 64bit), Iit may depend on systems like NAS-devices which may be limited in their tooling.

## docker-compose
If you get docker-compose running you may do a git clone of this repo and add the following to a new file named docker-compose.yml
```
version: "3"

services:
  chia:
    container_name: chia
    build:
       context: .
       args:
             BRANCH: 1.1.3
    ports:
      - "8444:8444/tcp"
      - "8555:8555/tcp"
    volumes:
      - ./plots:/plots
    restart: always
```
- explanation
   - BRANCH 1.1.3 -> as far as I see 1.1.3 seems to be the latest stable version for now
   - ./plots maps a local plots dir to the internal plots-dir
- after that you can start it with `docker-compose up -d`
- this builds the image locally on your device and starts the container afterwards

## docker only
- git clone this repo
- docker build --build-arg BRANCH=1.1.3 -t chia:latest
- after that you can use chia:latest (your local build image) instead of ghcr.io/chia-network/chia:latest
`docker run --name <container-name> -d chia:latest`
