### ISSUE TITLE
Multiple plot drives 

### ISSUE THREAD

**Issue by tdworm** [Chia-Network/chia-docker#201]
Trying to mount 10 separate drives that contain my plots. Cannot find the right format to get beyond the first drive. Using :/plots for all does work for any; using :/plots for the first and then numbering all the additional drives only shows the plots on the first drive (:/plots). 

Many thanks in advance for any guidance.

**Comment by Starttoaster** [comment]
Hi, you have a couple of options depending on if you want to use the recursive directory plot scanning feature.

### With recursive plot scan

Just put all of your plot drives as subdirectories to one over-arching directory like so (just showing plot-related config portion):

```
version: "3.6"
services:
  chia:
    image: ghcr.io/chia-network/chia:latest
    environment:
      recursive_plot_scan: "true"
      plots_dir: "/plots"
    volumes:
      - /path/to/plots1:/plots/dir1
      - /path/to/plots2:/plots/dir2
      - /path/to/plots3:/plots/dir3
```

### Without recursive plot scan

Just use the plots_dir environment variable to specify all your plot directories. If you're familiar with linux, it uses the normal PATH-style colon-separated list convention (just showing plot-related config portion):

```
version: "3.6"
services:
  chia:
    image: ghcr.io/chia-network/chia:latest
    environment:
      plots_dir: "/plots/dir1:/plots/dir2:/plots/dir3"
    volumes:
      - /path/to/plots1:/plots/dir1
      - /path/to/plots2:/plots/dir2
      - /path/to/plots3:/plots/dir3
```
