### ISSUE TITLE
SSL keys permission 

### ISSUE THREAD

**Issue by SalimiHabib** [Chia-Network/chia-docker#222]
i try below mount in my compose file  , it contain bind mount that use   /mnt/chia/ on host to share SSL keys with another container 

```
volumes:
  - type: bind
    source: /mnt/chia/
    target: /root/.chia
  - type: bind
    source: /mnt/chia/chia_keys/
    target: /root/.chia_keys

```
also my environment is :

```
environment:
    TZ: "Europe/Istanbul"
    keys: "persistent"
    upnp: "false"
    self_hostname: "0.0.0.0"


```
    
**it works well until restart .**

after chia docker restart it automatically change permission of keys inside SSL directory and other container cannot access it for use keys to made connection.
 
i use swarm and need this be automatic and no need to change permissions on container restart.

but after changing permission manually  (on host directory ) it works fine .

how to solve this problem ?

thank you

**Comment by Starttoaster** [comment]
Hi @SalimiHabib , to solve this problem what you'll actually have to do is copy the `config/ssl/ca` directory from one of the containers to a different path on your host, mount it in the second container in a location like `/ca` and then set an environment variable that tells the chia-docker entrypoint script where your CA is located, like so (assuming docker command line, change this for your swarm service file) `-e ca=/ca`.

You can also copy one of the `config/ssl/ca` directories from either one of your two containers you mentioned here, and mount it to `/ca` in both containers too if you so prefer. But the general idea here is that you never want two chia-docker containers just using the same CHIA_ROOT.

Note that I haven't ran this docker-compose file myself, but just created this as an example of what I'm talking about, which you could translate to your own swarm service file. This just uses an example farmer and harvester setup, the example would be similar enough for two other chia services using a common certificate authority as well:

```yaml
version: "3.6"
services:
  farmer:
    container_name: farmer
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    environment:
      service: farmer-only
      ca: /ca
      keys: persistent
    volumes:
      - /mnt/farmer/.chia:/root/.chia
      - /mnt/chia/chia_keys:/root/.chia_keys
      - /mnt/ca:/ca

  harvester:
    container_name: harvester
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:latest
    environment:
      service: harvester
      farmer_address: farmer
      farmer_port: 8447
      ca: /ca
      keys: none
    volumes:
      - /mnt/plots:/plots
      - /mnt/harvester/.chia:/root/.chia
      - /mnt/ca:/ca
```
