### ISSUE TITLE
exposing port  9256 

### ISSUE THREAD

**Issue by SalimiHabib** [Chia-Network/chia-docker#225]
i use this image in swarm stack and my compose file ports is as below  
```

 ports:
   - "9256:9256"
   - "8444:8444"
   - "8555:8555"
 environment:
     TZ: "Europe/Istanbul"
     keys: "persistent"
     upnp: "false"
     self_hostname: "0.0.0.0"
     healthcheck: "false"
     log_to_file: "false"


```
but in container i get this with no "9256:9256" port 
```

"Config": {
        "Hostname": "ea475b48db9c",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8444/tcp": {},
            "8555/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [


```

is there any need to change config file to access wallet in RPC , what is problem ?

thank you
