### ISSUE TITLE
chia keys add not saved while volumes are mounted

### ISSUE THREAD

**Issue by maxouille** [Chia-Network/chia-docker#285]
Hi, 

I can't make the container work as intended. I have a very simple docker compose file that only start the container, but not farming. Then I enter the container to add my key with the mnemonic. I can add the key properly but when I restart the container, my old key has disappeared and `chia keys show` returns "There are no saved private keys".  

Here is the docker compose file : 
```
services:
  chia:
    image: ghcr.io/chia-network/chia:latest
    container_name: chia
    restart: unless-stopped
    volumes:
      - ./config:/root/.chia/mainnet
      - /mnt/data/chia/mainnet/db:/root/.chia/mainnet/db
      - /mnt/hdd8to/chia:/plots
    environment:
      - TZ=Europe/Paris
      - keys=""
    ports:
      - "8444:8444"
```

Thank you for your help, it has been 2 days since i'm trying to make it work...
