### ISSUE TITLE
Docker Stack Deploy runnign into issues.

### ISSUE THREAD

**Issue by JamesM92** [Chia-Network/chia-docker#93]
I am trying to use the docker stack to deploy the chia docker, but i can't seem to get it to recognize the key file, get it to remember the keys i pass to it in command, or get it to start farming plots.

-I can get it to remember the keys by passing them in via command, but everytime i boot it up it creates new keys.

The keyring instruction is a bit of a red herring, as it only applies if you have a keyring application managing it, otherwise you need to tell the chia inside the docker to reference your CA

you need to move the CA folder from your original computer into a tmp folder, shut down the chia processes, then restart it with `venv/bin/chia init -c "location/of/ca/folder"   ` this will have it import the CA and implement it into the other folders inside the mainnet/config/ssl directory]

```

volumes:
  root:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/ChiaCoin/_data/root/
      #this is where you want the persistant data for chia to live
      #start with this empty
          
  plots-final:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/coin/
      #this directory is where you want the plots to be read from
      #this can have plots before you create the docker

  keyring:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dev-disk-by-label-Archive/portainer/ChiaCoin/_data/keyring/
      #if importing settings from another machine, this is where it is stored
      # you will need to pass in your CA folder from your starting machine here
          # to pass in the Ca settings
              # venv/bin/chia stop -d all
              # venv/bin/chia init -c /key/ca/
              # venv/bin/chia start all
              # this will import the CA certs and apply them to the other services as needed.
      
services:
  chia:
    image: ghcr.io/chia-network/chia:latest
    container_name: chia_main
    restart: always
    volumes:
      - root:/root/.chia/
      - plots-final:/plots/
      - keyring:/key/
    ports:
      - 8447:8447 #open this port so harvesters can use this as the primary.
    environment:
      - PLOTS_DIR=/plots/

    
```
